services:
  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
#    expose:
#      - "${POSTGRES_PORT:-5432}"
    ports:
      - "5432:5432"

  zookeeper:
    image: bitnami/zookeeper
    expose:
      - "${ZOOKEEPER_PORT:-2181}"

  kafka:
    image: bitnami/kafka
#    expose:
#      - "${KAFKA_PORT:-9092}"
    ports:
      - '9092:9092'

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: