"""init

Revision ID: 7e1f662eddd7
Revises: 
Create Date: 2023-03-23 16:18:34.630298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e1f662eddd7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list',
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_list_title'), 'list', ['title'], unique=False)
    op.create_table('note',
    sa.Column('text', sa.String(length=256), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'DONE', name='statusenum'), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    op.drop_index(op.f('ix_list_title'), table_name='list')
    op.drop_table('list')
    # ### end Alembic commands ###
