apiVersion: v1
kind: ConfigMap
metadata:
  name: core-config
data:
  DATABASE_URL: "postgresql+asyncpg://postgres:postgres@postgres-core-svc:5432/postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-svc:9093"